// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace hitster_mapper_server.Migrations
{
    [DbContext(typeof(HitsterContext))]
    partial class HitsterContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("hitster_mapper_server.Entity.HitsterCard", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("CardNumber")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("HitsterGameSetId")
                        .HasColumnType("int");

                    b.Property<string>("Spotify")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("HitsterGameSetId");

                    b.ToTable("HitsterCard");
                });

            modelBuilder.Entity("hitster_mapper_server.Entity.HitsterGameSet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("SetName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("HitsterGameSet");
                });

            modelBuilder.Entity("hitster_mapper_server.Entity.HitsterCard", b =>
                {
                    b.HasOne("hitster_mapper_server.Entity.HitsterGameSet", null)
                        .WithMany("SetCards")
                        .HasForeignKey("HitsterGameSetId");
                });

            modelBuilder.Entity("hitster_mapper_server.Entity.HitsterGameSet", b =>
                {
                    b.Navigation("SetCards");
                });
#pragma warning restore 612, 618
        }
    }
}
